name: Build

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET 5.0
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '5.0.403'
    - name: Run Card Scraper
      run: dotnet run -c Release --project SharpScraper/CardScraper/CardScraper.csproj -- args XML output.xml https://www.pokemonwizard.com/cards/123436/pikachu-ex-xy124
